name: GitHub Actions Heroku Production Deployment CI/CD Pipeline

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Configure Heroku credentials
        run: |
          echo "machine api.heroku.com" > ~/.netrc
          echo "  login ${{ secrets.HEROKU_API_KEY }}" >> ~/.netrc
          echo "  password ${{ secrets.HEROKU_API_KEY }}" >> ~/.netrc
          echo "machine git.heroku.com" >> ~/.netrc
          echo "  login ${{ secrets.HEROKU_API_KEY }}" >> ~/.netrc
          echo "  password ${{ secrets.HEROKU_API_KEY }}" >> ~/.netrc
          chmod 600 ~/.netrc
          
      - name: Add Heroku remote
        run: git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git || true

      - name: Stash local changes
        run: git stash --include-untracked

      - name: Pull from Heroku
        run: git pull heroku main --rebase

      - name: Apply stashed changes
        run: git stash pop

      - name: Deploy to Heroku
        run: git push heroku main --force
